version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /Frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      react-packages:
        patterns:
          - 'react'
          - 'react-dom'

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      ef-core:
        patterns:
          - 'Microsoft.EntityFrameworkCore*'
      microsoft-extensions:
        patterns:
          - 'Microsoft.Extensions.*'
      testing-framework:
        patterns:
          - 'xunit*'
          - 'RichardSzalay.MockHttp*'
