import type { Metadata } from 'next'
import '@/styles/globals.scss'
import { plusJakartaSans, cormorantGaramond, quickSand } from '@/constants/fonts'
import Nav from '@/components/Nav/Nav'
import Footer from '@/components/Footer/Footer'

export const metadata: Metadata = {
	title: 'Yuume',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className={`${plusJakartaSans.variable} ${cormorantGaramond.variable} ${quickSand.variable}`}>
			<body>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	)
}
